### ISSUE TITLE
--option required, results in 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by salkinium** [dergraaf/library-builder#1]
Running the `lbuild` script using the following `project.xml`:

``` xml
<library>
  <options>
    <option name="::testbench" value="True" />
  </options>
  <modules>
    <module>:ws2812</module>
  </modules>
</library>
```

results in this error:

```
 $ ../library-builder/scripts/lbuild -r ../loa-hdl/loa-hdl.lb -c project.xml
None
Traceback (most recent call last):
  File "../library-builder/scripts/lbuild", line 84, in <module>
    parser.configure_and_build_library(args.config, args.outpath, args.options)
  File "/Users/niklas/development/library-builder/scripts/../lbuild/parser.py", line 385, in configure_and_build_library
    commandline_options = self.format_commandline_options(cmd_options)
  File "/Users/niklas/development/library-builder/scripts/../lbuild/parser.py", line 377, in format_commandline_options
    for option in cmd_options:
TypeError: 'NoneType' object is not iterable
```

Calling it with an option does seem to fix it though.

```
 $ ../library-builder/scripts/lbuild -r ../loa-hdl/loa-hdl.lb -c project.xml -D "::testbench=True"
```

It doesn't seem to be a very useful default setting…

**Comment by dergraaf** [comment]
Please use the latest version. Issue already fixed in 2584b4112c99e2e71c6715847ae183993ffeff20
